#'plot_npx_norm_qc (Generate QC plots pre and post normalization)
#'@description Pot the normalization QC plot, generate the reference sample's analytes' pre vs post normalization scatter plot, colored by plates
#'@param normed_se a summarizedexperiment, normaly generated by cmb_npx_sc() after normalization
#'@param bridge_pattern regex to identify reference sample
#'@param fields colData name from which to identify the reference samples uing the regexp.
#'@export
#'@md
#'
plot_npx_norm_qc <- function(normed_se, bridge_pattern= "hd", fields = "Assay"){

  bridge <- normed_se[, grep(bridge_pattern, normed_se[[fields]])]

  assay_ls <- names(bridge@assays@data)
  bridge_data_ls <- lapply(assay_ls, function(x){
    bridge@assays@data[[x]] %>%
      data.frame()%>%
      set_colnames(value = bridge$f_name)%>%
      rownames_to_column(var = "Analyt") %>%
      gather(-Analyt, key = "f_name", value = "value")%>%
      mutate(Assay = x,
             f_name = gsub("^.*/", "", f_name))
  })
  bridge_data_ls <- do.call(rbind, bridge_data_ls)

  normed_se_ls <- lapply(assay_ls, function(x){
    normed_se@assays@data[[x]] %>%
      data.frame()%>%
      set_colnames(value = normed_se$f_name)%>%
      rownames_to_column(var = "Analyt") %>%
      gather(-Analyt, key = "f_name", value = "value")%>%
      mutate(Assay = x,
             f_name = gsub("^.*/", "", f_name))
  })
  normed_se_ls <- do.call(rbind, normed_se_ls)

  p1 <- bridge_data_ls %>%
    mutate(Assay = factor(Assay, levels = names(normed_se@assays@data)))%>%
    ggplot()+
    geom_point(aes(value, Analyt, color = f_name), shape = 21, size = 4)+
    geom_point(aes(LOD, Analyt),
               data = data.frame(normed_se@elementMetadata)%>%
                 mutate(Analyt = make.names(Analyt)))+
    labs(title = "Normalization Reference")+
    facet_grid( ~ Assay)+
    theme_bw()+
    theme(legend.position = "bottom")+
    guides(color=guide_legend(nrow=2,byrow=TRUE))+
    theme(axis.text.x = element_text(angle = 60, hjust = 1))

  return(p1)
}
